{% set name = "wurlitzer" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0144228960a992ef46e339e8aa560600bd34cd64e018bfebad88c0dd61bd8ba5

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wurlitzer

about:
  home: https://github.com/minrk/wurlitzer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Capture C-level stdout/stderr in Python

extra:
  recipe-maintainers:
    - minrk
    - bjodah
    - asmeurer
    - ccordoba12
